    # """Add is_offline column to Product model
    # 
    # Revision ID: 421d7b8ab8c8
    # Revises: 29871cf7c5f5
    # Create Date: 2024-12-20 22:04:50.460958
    # 
    # """
    # 从alembic导入op对象
    from alembic import op
    # 导入sqlalchemy库
    import sqlalchemy as sa


    # # revision identifiers, used by Alembic.
    # 定义版本号
    revision = '421d7b8ab8c8'
    # 定义前一个版本号
    down_revision = '29871cf7c5f5'
    # 定义分支标签，这里为None
    branch_labels = None
    # 定义依赖，这里为None
    depends_on = None


    # 定义升级函数
    def upgrade():
        # # ### commands auto generated by Alembic - please adjust! ###
        # 使用op.batch_alter_table批量修改表结构
        with op.batch_alter_table('product', schema=None) as batch_op:
            # 为product表添加is_offline列，数据类型为布尔值，可空
            batch_op.add_column(sa.Column('is_offline', sa.Boolean(), nullable=True))

        # # ### end Alembic commands ###


    # 定义降级函数
    def downgrade():
        # # ### commands auto generated by Alembic - please adjust! ###
        # 使用op.batch_alter_table批量修改表结构
        with op.batch_alter_table('product', schema=None) as batch_op:
            # 从product表删除is_offline列
            batch_op.drop_column('is_offline')

        # # ### end Alembic commands ###
