exclude:
- sdist/
- .env
- '*.swo'
- lib/
- '*.bak'
- '*.swp'
- '*.egg-info/'
- html_encoding_fix.md
- .installed.cfg
- .idea/
- '*.so'
- .eggs/
- Thumbs.db
- '*.vscode'
- '*.log'
- '*$py.class'
- eggs/
- auto_push.log
- __pycache__/
- commented_test*/
- .git
- test_output/
- downloads/
- .venv
- .DS_Store
- .env.*
- '*.egg'
- env/
- '*.venv'
- .Python
- dist/
- build/
- .vscode/
- force_push.py
- /test
- test_encoding_output/
- test_folder/
- commented/
- temp/
- var/
- '*.tmp'
- parts/
- lib64/
- /output
- push_history.txt
- auto_push.py
- auto_push_after_run.py
- '*.py[cod]'
- commented_test/
- develop-eggs/
- test
